### PR TITLE
Change aws policy template rendering

### PR DESCRIPTION
**Pull request by QuentinBisson**
### What this PR does / why we need it

Towards https://github.com/giantswarm/roadmap/issues/3127

This needs to be tested but this allows us to configure extra bucket access for an aws role for the mimir ruler as the role needs to be able to access both the block-storage buckets and the ruler one

### Checklist

- [x] Update changelog in CHANGELOG.md.

Making this a draft because I need to test it first

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
Logs from the pod on `golem` when deploying it : 
```
2024-02-14T16:14:14Z    INFO    Observed a panic in reconciler: template: rolePolicy:13: function "_" not defined       {"controller": "bucket", "controllerGroup": "objectstorage.giantswarm.io", "controllerKind": "Bucket", "Bucket": {"name":"giantswarm-golem-loki","namespace":"loki"}, "namespace": "loki", "name": "giantswarm-golem-loki", "reconcileID": "261ab806-f683-43b1-95b8-c19d2d09a05b"}
panic: template: rolePolicy:13: function "_" not defined [recovered]
        panic: template: rolePolicy:13: function "_" not defined

goroutine 139 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x1df1ba0?, 0xc0001152b0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/giantswarm/object-storage-operator/internal/pkg/service/objectstorage/cloud/aws.NewIamService(_, {{_, _}, _}, {_, _}, {{0x2457280, 0xc000050a20}, {0x7ffd52755755, 0x5}, ...})
        /workspace/internal/pkg/service/objectstorage/cloud/aws/iam.go:36 +0x365
github.com/giantswarm/object-storage-operator/internal/pkg/service/objectstorage/cloud/aws.AWSObjectStorageService.NewAccessRoleService({}, {0x244d458, 0xc0007846c0}, {{0x2451220?, 0xc0007846f0?}, 0xc000274230?}, {0x24507b8, 0xc000274230})
        /workspace/internal/pkg/service/objectstorage/cloud/aws/service.go:48 +0x456
github.com/giantswarm/object-storage-operator/internal/controller.BucketReconciler.Reconcile({{0x2457280, 0xc000050a20}, {0x2424500, 0xc000311140}, {0x242c928, 0x33f4320}, {{0x7ffd527556fc, 0x10}, {0x7ffd52755755, 0x5}, ...}}, ...)
        /workspace/internal/controller/bucket_controller.go:73 +0x62d
```

**Comment by QuentinBisson** [comment]
:(

**Comment by QuantumEnigmaa** [comment]
With the current state : 
```
2024-02-15T08:54:03Z    ERROR   Reconciler error        {"controller": "bucket", "controllerGroup": "objectstorage.giantswarm.io", "controllerKind": "Bucket", "Bucket": {"name":"giantswarm-golem-mimir-ruler","namespace":"mimir"}, "namespace": "mimir", "name": "giantswarm-golem-mimir-ruler", "reconcileID": "6719b973-252f-4e1f-b86a-fe9f6ca5eb5e", "error": "operation error IAM: PutRolePolicy, https response error StatusCode: 400, RequestID: 1b2e3068-cfb2-42ec-b357-3614a7e735f5, api error ValidationError: The specified value for policyDocument is invalid. It must contain only printable ASCII characters.", "errorVerbose": "operation error IAM: PutRolePolicy, https response error StatusCode: 400, RequestID: 1b2e3068-cfb2-42ec-b357-3614a7e735f5, api error ValidationError: The specified value for policyDocument is invalid. It must contain only printable ASCII characters.\ngithub.com/giantswarm/object-storage-operator/internal/pkg/service/objectstorage/cloud/aws.IAMAccessRoleServiceAdapter.ConfigureRole\n\t/workspace/internal/pkg/service/objectstorage/cloud/aws/iam.go:171\ngithub.com/giantswarm/object-storage-operator/internal/controller.BucketReconciler.reconcileNormal\n\t/workspace/internal/controller/bucket_controller.go:137\ngithub.com/giantswarm/object-storage-operator/internal/controller.BucketReconciler.Reconcile\n\t/workspace/internal/controller/bucket_controller.go:84\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695\ngithub.com/giantswarm/object-storage-operator/internal/controller.BucketReconciler.reconcileNormal\n\t/workspace/internal/controller/bucket_controller.go:139\ngithub.com/giantswarm/object-storage-operator/internal/controller.BucketReconciler.Reconcile\n\t/workspace/internal/controller/bucket_controller.go:84\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"
```

**Comment by QuentinBisson** [comment]
Latest version:
```

namespace": "mimir", "name": "giantswarm-golem-mimir-ruler", "reconcileID": "a38019e9-6ffe-4f50-a082-410a5e035c4e"}
2024-02-15T09:04:45Z	INFO	setting role policy for role giantswarm-golem-mimir-ruler with data {giantswarm-golem-mimir-ruler [giantswarm-golem-mimir]} renders the following policy {
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Action": [
				"s3:ListBucket",
				"s3:PutObject",
				"s3:GetObject",
				"s3:DeleteObject"
			],
			"Resource": [
				
				"arn:aws:s3:::giantswarm-golem-mimir",
				"arn:aws:s3:::giantswarm-golem-mimir/*",
				
				"arn:aws:s3:::giantswarm-golem-mimir-ruler",
				"arn:aws:s3:::giantswarm-golem-mimir-ruler/*"
			]
		},
		{
			"Effect": "Allow",
			"Action": [
				"s3:GetAccessPoint",
				"s3:GetAccountPublicAccessBlock",
				"s3:ListAccessPoints"
			],
			"Resource": "*"
		}
	]
}	{"controller": "bucket", "controllerGroup": "objectstorage.giantswarm.io", "controllerKind": "Bucket", "Bucket": {"name":"giantswarm-golem-mimir-ruler","namespace":"mimir"}, "namespace": "mimir", "name": "giantswarm-golem-mimir-ruler", "reconcileID": "a38019e9-6ffe-4f50-a082-410a5e035c4e"}
2024-02-15T09:04:45Z	INFO	Bucket access role created	{"controller": "bucket", "controllerGroup": "objectstorage.giantswarm.io", "controllerKind": "Bucket", "Bucket": {"name":"giantswarm-golem-mimir-ruler","namespace":"mimir"}, "namespace": "mimir", "name": "giantswarm-golem-mimir-ruler", "reconcileID": "a38019e9-6ffe-4f50-a082-410a5e035c4e"}
2024-02-15T09:04:45Z	INFO	Finished reconciling Bucket	{"controller": "bucket", "controllerGroup": "objectstorage.giantswarm.io", "controllerKind": "Bucket", "Bucket": {"name":"giantswarm-golem-mimir-ruler","namespace":"mimir"}, "namespace": "mimir", "name": "giantswarm-golem-mimir-ruler", "reconcileID": "a38019e9-6ffe-4f50-a082-410a5e035c4e"}

```

**Comment by QuentinBisson** [comment]
Removed log line

**Review by QuantumEnigmaa — APPROVED** [review]
Let's go !

**Pull request merged**
